version: '3.7'
services:
  api:
    image: graphile/postgraphile:4
    command: "--retry-on-init-fail --connection postgres://postgres@db/postgres"
    init: true
    ports:
      - 5000:5000
    depends_on: 
      - db
  db:
    build: db
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: